Remove cruft after change to Posix compliant. Rearrange to keep functions written the same way.

diff --git a/authdns b/authdns
--- a/authdns
+++ b/authdns
@@ -4,7 +4,16 @@
 #
 
 # Check for dig commannd
-command -v dig >/dev/null 2>&1 || { echo >&2 "Oops! The dig command is necessary for this script, but was not found on this system :(  Aborting."; exit 1; }
+verify_tools() {
+    command -v dig >/dev/null 2>&1 || { echo >&2 "Oops! The dig command is necessary for this script, but was not found on this system :(  Aborting."; exit 1; }
+}
+
+# Check input
+check_input() {
+    if [ -z ${dom} ]; then
+        echo 'Please specify a domain.'; exit 1;
+    fi
+}
 
 # Get input, initial variables
 dom=${1}
@@ -23,16 +32,7 @@ get_result() {
 
 set_colors() {
     # Colors and formatting
-    # Mac
-    if [ "`uname`" = "Darwin" ];
-       then
-       greenbold='\033[0;32m'
-
-       # Linux
-       else
-       #greenbold='\E[32;1m'
-       greenbold='\033[1;32m'
-    fi;
+    greenbold='\033[1;32m'
     clroff="\033[0m";
 }
 
@@ -61,23 +61,16 @@ print_results() {
     printf "%b\n" "${dig_result}\n"
     printf "%b\n" "${greenbold}Nameserver Names:\n${clroff}${auth_ns}\n"
     printf "%b\n" "${greenbold}Nameserver IPs:\n${clroff}${bare_result}\n"
-#	echo -e $greenbold"\n# dig NS ${tld}. +short | head -n1"$clroff
-#	echo $tld_server
-#	echo -e $greenbold"\n# "$dig_oneliner$clroff
-#	echo -e "${dig_result}\n"
-#	echo -e $greenbold"Nameserver Names: \n"$clroff"${auth_ns}\n"
-#	echo -e $greenbold"Nameserver IP's: \n"$clroff"${bare_result}\n"
 }
 
 
-# Check input, run code
-if [ -z ${dom} ]; then
-echo 'Please specify a domain.'
-else
-	create_dig_oneliner
-	get_result
-	set_colors
-	get_nameservers
-	get_nameserver_ips
-	print_results
-fi
+
+# Run code
+verify_tools
+check_input
+create_dig_oneliner
+get_result
+set_colors
+get_nameservers
+get_nameserver_ips
+print_results
